### ISSUE TITLE
SNAP Graph Problem

### ISSUE THREAD

**Issue by maksud** [cuStinger/cuStinger#2]
I have downloaded and build the code without any problem. But when I try to run the code, I get the following error:

$ ./cuMain ~/ca-AstroPh.txt astro-ph
Warning: SNAP reader may relabel vertex IDs
Original input: 18772 vertices, 396160 edges
Processed 18772 vertices, 396160 edges
astro-ph,18772,396160,1,0.0268225,1Execution error = Error in the first update sweep: invalid device function from file /home/abcd/git/cuStinger/src/cuStingerInsertions.cu, line 206

What is the problem?

**Comment by ogreen** [comment]
@maksud , what GPU are you using for your benchmarking?
I am able to run your exact example on a  P100.

**Comment by maksud** [comment]
I am using GeForce GTX 1080 and using Cuda compilation tools, release 8.0, V8.0.44. I tried to run this on my Macbook, but the similar problem persists.

**Comment by ogreen** [comment]
Can you pull a new version. I have patched the CMakeList.txt file to support newer devices. I thought that had already been resolved.

**Comment by maksud** [comment]
Wow, worked well. Thanks for the quick fix. I am trying to develop new graph algorithm on GPU and this seems very relevant.

**Comment by ogreen** [comment]
Good luck.
